"""``deep-dream explore`` — multi-strategy semantic exploration.

Combines five retrieval strategies into a single unified result set:

1. **Document file search** — grep-like line matches across indexed files.
2. **Semantic concept search** — embedding similarity against the concept graph.
3. **Graph neighbour expansion** — walk outward from seed concepts.
4. **Relation evidence collection** — find co-mention evidence for concept pairs.
5. **Evidence card assembly** — merge raw file hits and graph source text into
   a unified card format.

Human output uses Rich panels and tables.  ``--json`` returns the same
structure as the legacy argparse command.
"""
from __future__ import annotations

import json as _json
from typing import Any, Dict, List

import click

from ._ctx import CliContext
from ._exit_codes import ERROR, OK
from ._output import OutputManager


def _to_dict(item: Any) -> dict:
    """Normalize an item to a plain dict.

    ``agent_semantic_search`` may return Entity DTO objects instead of
    dicts.  This helper ensures safe ``.get()`` access in all cases.
    """
    if isinstance(item, dict):
        return item
    if hasattr(item, "__dict__"):
        return vars(item)
    return {}


# ------------------------------------------------------------------
# Click command
# ------------------------------------------------------------------

@click.command()
@click.argument("question")
@click.option(
    "--graph",
    default=None,
    help="Graph ID to query (defaults to the active graph).",
)
@click.option(
    "--role",
    type=click.Choice(["document", "episode", "entity", "relation"]),
    default=None,
    help="Semantic search role filter.",
)
@click.option(
    "--limit",
    type=int,
    default=20,
    show_default=True,
    help="Maximum total semantic results.",
)
@click.option(
    "--threshold",
    type=float,
    default=0.2,
    show_default=True,
    help="Minimum similarity threshold for semantic search.",
)
@click.option(
    "--file-limit",
    type=int,
    default=20,
    show_default=True,
    help="Maximum total document file hits.",
)
@click.option(
    "--per-term-file-limit",
    type=int,
    default=5,
    show_default=True,
    help="Maximum file hits per individual query term.",
)
@click.option(
    "--expand-query/--no-expand-query",
    default=True,
    show_default=True,
    help="Use all expanded query terms (not just the first).",
)
@click.option(
    "--terms",
    default=None,
    help="Comma-separated query expansion terms generated by the caller/agent.",
)
@click.option(
    "--semantic-queries",
    type=int,
    default=5,
    show_default=True,
    help="Maximum number of query terms used for semantic search.",
)
@click.option(
    "--min-semantic-score",
    type=float,
    default=0.0,
    show_default=True,
    help="Discard semantic results below this score.",
)
@click.option(
    "--evidence-limit",
    type=int,
    default=12,
    show_default=True,
    help="Maximum number of assembled evidence cards.",
)
@click.option(
    "--neighbor-seeds",
    type=int,
    default=3,
    show_default=True,
    help="Number of top semantic concepts used as seeds for neighbour expansion.",
)
@click.option(
    "--neighbor-limit",
    type=int,
    default=50,
    show_default=True,
    help="Maximum number of neighbour results.",
)
@click.option(
    "--depth",
    type=int,
    default=1,
    show_default=True,
    help="Graph traversal depth for neighbour expansion.",
)
@click.option(
    "--relation-seed-count",
    type=int,
    default=5,
    show_default=True,
    help="Number of top concepts used to build relation pairs.",
)
@click.option(
    "--relation-pair-limit",
    type=int,
    default=8,
    show_default=True,
    help="Maximum number of concept pairs checked for relations.",
)
@click.option(
    "--relation-evidence-limit",
    type=int,
    default=10,
    show_default=True,
    help="Maximum total relation evidence rows.",
)
@click.pass_context
def explore(
    ctx: click.Context,
    question: str,
    graph: str | None,
    role: str | None,
    limit: int,
    threshold: float,
    file_limit: int,
    per_term_file_limit: int,
    expand_query: bool,
    terms: str | None,
    semantic_queries: int,
    min_semantic_score: float,
    evidence_limit: int,
    neighbor_seeds: int,
    neighbor_limit: int,
    depth: int,
    relation_seed_count: int,
    relation_pair_limit: int,
    relation_evidence_limit: int,
) -> None:
    """Multi-strategy semantic exploration of the concept graph.

    QUESTION is the natural-language query to explore.  The command searches
    raw documents, runs semantic concept lookups, expands into graph
    neighbours, and collects relation evidence -- returning everything in
    a single unified result set.
    """
    from core.explore import ExploreOptions, explore_memory

    out = OutputManager(ctx)
    cli_ctx: CliContext = ctx.obj

    graph_id = cli_ctx.get_active_graph(explicit=graph)

    with cli_ctx.get_storage(graph_id) as storage:
        with out.spinner("Exploring documents, episodes, concepts, and relations..."):
            data = explore_memory(
                storage,
                question,
                explicit_terms=terms,
                expand_query=expand_query,
                options=ExploreOptions(
                    role=role,
                    limit=limit,
                    threshold=threshold,
                    file_limit=file_limit,
                    per_term_file_limit=per_term_file_limit,
                    semantic_queries=semantic_queries,
                    min_semantic_score=min_semantic_score,
                    evidence_limit=evidence_limit,
                    neighbor_seeds=neighbor_seeds,
                    neighbor_limit=neighbor_limit,
                    depth=depth,
                    relation_seed_count=relation_seed_count,
                    relation_pair_limit=relation_pair_limit,
                    relation_evidence_limit=relation_evidence_limit,
                ),
            )

        meta = {
            "graph_id": graph_id,
            "used": {
                "raw_files": True,
                "episodes": True,
                "sqlite": True,
                "semantic": True,
                "graph_traversal": True,
                "api": False,
            },
        }

    # ------------------------------------------------------------------
    # Output
    # ------------------------------------------------------------------
    if out.is_json:
        from ._output import json_result

        payload = json_result("explore", data, meta=meta)
        click.echo(_json.dumps(payload, ensure_ascii=False, indent=2))
        return

    _render_human(out, data, meta)


# ------------------------------------------------------------------
# Rich human-readable rendering
# ------------------------------------------------------------------

def _render_human(
    out: OutputManager,
    data: Dict[str, Any],
    meta: Dict[str, Any],
) -> None:
    """Render the explore results as Rich panels and tables."""
    from rich.panel import Panel
    from rich.markup import escape as _esc
    from rich.table import Table
    from rich.text import Text

    from ._helpers import compact_text

    coverage = data["coverage"]

    # -- Header panel ---------------------------------------------------
    header_lines = [
        f"[bold]Question:[/bold] {_esc(data['question'])}",
        f"[bold]Graph:[/bold]   {_esc(meta.get('graph_id', '?'))}",
    ]
    terms_display = ", ".join(
        _esc(t["term"]) for t in data.get("query_terms", [])
    )
    if terms_display:
        header_lines.append(f"[bold]Terms:[/bold]    {terms_display}")
    out.console.print(Panel(
        "\n".join(header_lines),
        title="Explore",
        border_style="cyan",
    ))

    # -- Coverage summary table -----------------------------------------
    cov_table = Table(
        title="Coverage Summary",
        show_header=True,
        header_style="bold",
        border_style="dim",
    )
    cov_table.add_column("Strategy", style="cyan", min_width=22)
    cov_table.add_column("Hits", justify="right", min_width=6)
    cov_table.add_column("Detail", min_width=20)
    cov_table.add_row(
        "Document file search",
        str(coverage["file_hits"]),
        f"per-term limit applied",
    )
    cov_table.add_row(
        "Semantic concept search",
        str(coverage["semantic_hits"]),
        f"threshold filtered",
    )
    cov_table.add_row(
        "Source evidence",
        str(coverage["source_evidence"]),
        "",
    )
    cov_table.add_row(
        "Evidence cards",
        str(coverage["evidence_cards"]),
        "merged file + graph",
    )
    cov_table.add_row(
        "Graph neighbours",
        str(coverage["neighbors"]),
        f"depth={data.get('depth', '?')}",
    )
    cov_table.add_row(
        "Relation evidence",
        str(coverage["relation_evidence"]),
        f"{coverage['relation_pairs_checked']} pairs checked",
    )
    out.console.print(cov_table)

    # -- File hits ------------------------------------------------------
    file_hits = data.get("file_hits", [])
    if file_hits:
        _render_file_hits(out, file_hits)
    else:
        out.console.print("[dim]No document file hits.[/dim]")

    # -- Semantic hits --------------------------------------------------
    semantic_hits = data.get("semantic_hits", [])
    if semantic_hits:
        _render_semantic_hits(out, semantic_hits)
    else:
        out.console.print("[dim]No semantic concept hits.[/dim]")

    # -- Neighbours -----------------------------------------------------
    neighbors = data.get("neighbors", [])
    if neighbors:
        _render_neighbors(out, neighbors)
    else:
        out.console.print("[dim]No graph neighbours found.[/dim]")

    # -- Relation evidence ----------------------------------------------
    rel_evidence = data.get("relation_evidence", [])
    if rel_evidence:
        _render_relation_evidence(out, rel_evidence)
    else:
        out.console.print("[dim]No relation evidence found.[/dim]")

    # -- Evidence cards -------------------------------------------------
    cards = data.get("evidence_cards", [])
    if cards:
        _render_evidence_cards(out, cards)
    else:
        out.console.print("[dim]No evidence cards assembled.[/dim]")

    out.console.print()


def _render_file_hits(out: OutputManager, hits: List[dict]) -> None:
    """Render document file hits as a Rich table."""
    from rich.table import Table

    table = Table(
        title="Document File Hits",
        show_header=True,
        header_style="bold",
        border_style="green",
    )
    table.add_column("#", justify="right", style="dim", min_width=3)
    table.add_column("Term", style="cyan", min_width=10)
    table.add_column("Title / Path", min_width=30)
    table.add_column("Line", justify="right", min_width=5)
    table.add_column("Excerpt", min_width=40, max_width=80)

    for idx, hit in enumerate(hits, 1):
        doc = hit.get("document") or {}
        title = doc.get("title") or doc.get("read_path") or "?"
        line = str(doc.get("line_start", ""))
        term = hit.get("matched_term", "")
        excerpt = hit.get("text", "")
        if len(excerpt) > 80:
            excerpt = excerpt[:77] + "..."
        table.add_row(str(idx), term, title, line, excerpt)
    out.console.print(table)


def _render_semantic_hits(out: OutputManager, hits: List[dict]) -> None:
    """Render semantic concept hits as a Rich table."""
    from rich.table import Table

    table = Table(
        title="Semantic Concept Hits",
        show_header=True,
        header_style="bold",
        border_style="magenta",
    )
    table.add_column("#", justify="right", style="dim", min_width=3)
    table.add_column("Score", justify="right", min_width=6)
    table.add_column("Family ID", style="cyan", min_width=12)
    table.add_column("Name", min_width=20)
    table.add_column("Query", style="dim", min_width=10)

    for idx, item in enumerate(hits, 1):
        score = f"{float(item.get('score') or item.get('_score') or 0.0):.3f}"
        fid = item.get("family_id", "")
        name = item.get("name") or item.get("target_name") or ""
        query = item.get("matched_query", "")
        table.add_row(str(idx), score, fid, name, query)
    out.console.print(table)


def _render_neighbors(out: OutputManager, neighbors: List[dict]) -> None:
    """Render graph neighbour expansion results as a Rich table."""
    from rich.table import Table

    table = Table(
        title="Graph Neighbours",
        show_header=True,
        header_style="bold",
        border_style="yellow",
    )
    table.add_column("#", justify="right", style="dim", min_width=3)
    table.add_column("Family ID", style="cyan", min_width=12)
    table.add_column("Name", min_width=20)
    table.add_column("Depth", justify="right", min_width=5)

    for idx, nb in enumerate(neighbors, 1):
        fid = nb.get("family_id", "")
        name = nb.get("name") or ""
        d = str(nb.get("depth", ""))
        table.add_row(str(idx), fid, name, d)
    out.console.print(table)


def _render_relation_evidence(out: OutputManager, evidence: List[dict]) -> None:
    """Render relation evidence rows as a Rich table."""
    from rich.table import Table

    from ._helpers import compact_text

    table = Table(
        title="Relation Evidence",
        show_header=True,
        header_style="bold",
        border_style="blue",
    )
    table.add_column("#", justify="right", style="dim", min_width=3)
    table.add_column("Relation", style="cyan", min_width=14)
    table.add_column("Entities", min_width=20)
    table.add_column("Source", min_width=20)
    table.add_column("Excerpt", min_width=40, max_width=80)

    for idx, ev in enumerate(evidence, 1):
        rel_name = ev.get("relation_name") or ev.get("relation_family_id", "")
        e1 = ev.get("entity1_name", "")
        e2 = ev.get("entity2_name", "")
        entities = f"{e1} -- {e2}" if e1 and e2 else e1 or e2 or "?"
        source = ev.get("title") or ev.get("read_path") or ""
        excerpt = compact_text(ev.get("source_text", ""))
        table.add_row(str(idx), rel_name, entities, source, excerpt)
    out.console.print(table)


def _render_evidence_cards(out: OutputManager, cards: List[dict]) -> None:
    """Render assembled evidence cards as Rich panels."""
    from rich.markup import escape as _esc
    from rich.panel import Panel

    from ._helpers import compact_text

    for idx, card in enumerate(cards, 1):
        claim = _esc(card.get("claim_hint", ""))
        doc = card.get("document") or {}
        title = _esc(doc.get("title") or doc.get("read_path") or "(no title)")
        verification = _esc(card.get("verification", ""))
        matched = [_esc(m) for m in card.get("matched_terms", [])]
        excerpt = _esc(card.get("source_excerpt", ""))

        body_parts: list[str] = []
        if claim:
            body_parts.append(f"[bold]Claim:[/bold] {claim}")
        body_parts.append(f"[bold]Document:[/bold] {title}")
        if verification:
            body_parts.append(f"[bold]Verification:[/bold] {verification}")
        if matched:
            body_parts.append(f"[bold]Matched terms:[/bold] {', '.join(matched)}")
        if excerpt:
            body_parts.append(f"[dim]{excerpt}[/dim]")

        concepts = card.get("concepts") or []
        if concepts:
            cpts = ", ".join(
                _esc(c.get("name", c.get("family_id", "?"))) for c in concepts
            )
            body_parts.append(f"[bold]Concepts:[/bold] {cpts}")

        episode = card.get("episode")
        if episode and episode.get("heading_path"):
            body_parts.append(
                f"[bold]Heading:[/bold] {_esc(episode['heading_path'])}"
            )

        out.console.print(Panel(
            "\n".join(body_parts),
            title=f"Evidence Card #{idx}",
            border_style="green",
        ))
